// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/gjtiquia/txt2ig/internal/web/templates/layouts"

func Watch(filePath string, initialImage string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script src=\"https://cdn.jsdelivr.net/npm/htmx-ext-sse@2.2.4/dist/sse.min.js\"></script> <div class=\"container mx-auto px-4 py-8 max-w-2xl\"><div class=\"mb-6\"><h1 class=\"text-3xl font-bold mb-2\">Live Preview</h1><p class=\"text-gray-400\">Watching: <code class=\"bg-gray-800 px-2 py-1 rounded\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(filePath)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/pages/watch.templ`, Line: 11, Col: 93}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</code></p><div id=\"connection-status\" class=\"mt-2 text-sm\"><span class=\"flex items-center gap-2\"><span class=\"w-2 h-2 rounded-full bg-green-500\"></span> Connected</span></div><div id=\"last-update\" class=\"mt-1 text-sm text-gray-500\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if initialImage != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<span>Last updated: </span><span id=\"update-time\"></span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<span>Waiting for initial render...</span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</div></div><div hx-ext=\"sse\" sse-connect=\"/sse/watch\" sse-swap=\"message\"><div id=\"preview-container\"><div id=\"loading\" class=\"htmx-indicator hidden mb-4\"><div class=\"flex items-center gap-2 text-yellow-500\"><div class=\"animate-spin w-4 h-4 border-2 border-yellow-500 border-t-transparent rounded-full\"></div><span>Regenerating...</span></div></div><div id=\"image-container\" class=\"bg-gray-800 rounded-lg overflow-hidden\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if initialImage != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<img src=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs("data:image/png;base64," + initialImage)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/pages/watch.templ`, Line: 39, Col: 53}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" alt=\"Preview\" class=\"w-full h-auto max-w-full\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<div class=\"text-gray-500 text-center py-16\">Waiting for initial render...</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div></div></div><div id=\"error-container\" class=\"mt-4\"></div></div><script>\n\t\t\tdocument.body.addEventListener('htmx:sseBeforeMessage', function(evt) {\n\t\t\t\ttry {\n\t\t\t\t\tconst data = JSON.parse(evt.detail.data);\n\t\t\t\t\t\n\t\t\t\t\tif (data.type === 'image') {\n\t\t\t\t\t\tdocument.getElementById('image-container').innerHTML = data.html;\n\t\t\t\t\t\tdocument.getElementById('loading').classList.add('hidden');\n\t\t\t\t\t\tdocument.getElementById('update-time').textContent = new Date().toLocaleTimeString();\n\t\t\t\t\t} else if (data.type === 'error') {\n\t\t\t\t\t\tdocument.getElementById('error-container').innerHTML = '<div class=\"bg-red-900 border border-red-700 text-red-100 px-4 py-3 rounded\">' + data.error + '</div>';\n\t\t\t\t\t\tdocument.getElementById('loading').classList.add('hidden');\n\t\t\t\t\t}\n\t\t\t\t} catch (e) {\n\t\t\t\t\tconsole.error('Error parsing SSE message:', e);\n\t\t\t\t}\n\t\t\t});\n\t\t\t\n\t\t\tdocument.body.addEventListener('htmx:sseOpen', function() {\n\t\t\t\tdocument.querySelector('#connection-status .rounded-full').classList.remove('bg-red-500');\n\t\t\t\tdocument.querySelector('#connection-status .rounded-full').classList.add('bg-green-500');\n\t\t\t});\n\t\t\t\n\t\t\tdocument.body.addEventListener('htmx:sseError', function() {\n\t\t\t\tdocument.querySelector('#connection-status .rounded-full').classList.remove('bg-green-500');\n\t\t\t\tdocument.querySelector('#connection-status .rounded-full').classList.add('bg-red-500');\n\t\t\t});\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base("txt2ig - Live Preview").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
