// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func TextForm(defaultConfig string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form id=\"convert-form\" hx-post=\"/convert\" hx-target=\"#result\" hx-indicator=\"#loading\" class=\"space-y-6\"><div><label for=\"text\" class=\"block text-sm font-medium mb-2\">Text</label> <textarea id=\"text\" name=\"text\" rows=\"8\" class=\"w-full bg-gray-800 border border-gray-700 rounded-lg p-4 text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-y min-h-[200px]\" placeholder=\"Enter your text here...\" required></textarea></div><details class=\"bg-gray-800 rounded-lg\"><summary class=\"cursor-pointer p-4 hover:bg-gray-700 rounded-lg\"><span class=\"font-medium\">Configuration (JSONC)</span></summary><div class=\"p-4 border-t border-gray-700\"><textarea id=\"config\" name=\"config\" rows=\"15\" class=\"w-full bg-gray-900 border border-gray-600 rounded p-3 text-white font-mono text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent\" placeholder=\"Enter config JSONC...\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(defaultConfig)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/components/text_form.templ`, Line: 28, Col: 20}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</textarea></div></details><div class=\"flex gap-4\"><button type=\"submit\" class=\"flex-1 bg-gradient-to-r from-blue-500 to-purple-600 text-white font-medium py-3 px-6 rounded-lg hover:from-blue-600 hover:to-purple-700 transition-all duration-200 text-lg\">Generate Image</button></div><div id=\"loading\" class=\"htmx-indicator hidden text-center\"><div class=\"inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-white\"></div><p class=\"mt-2\">Generating image...</p></div></form><div id=\"result\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
