// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/gjtiquia/txt2ig/internal/watch/templates/layouts"

func Preview(fileName, configName, imageBase64 string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container mx-auto px-4 py-8 max-w-4xl\"><div class=\"mb-6\"><h1 class=\"text-2xl font-bold text-white mb-2\">Watching: ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fileName)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/preview.templ`, Line: 9, Col: 71}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</h1><p class=\"text-gray-400\">Config: ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(configName)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/preview.templ`, Line: 10, Col: 49}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</p></div><div id=\"connection-status\" class=\"mb-4 flex items-center gap-2\"><div class=\"rounded-full w-3 h-3 bg-red-500\"></div><span class=\"text-gray-400 text-sm\">Disconnected</span></div><div class=\"mb-4\"><img src=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs("data:image/png;base64," + imageBase64)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `pages/preview.templ`, Line: 20, Col: 49}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" alt=\"Preview\" class=\"w-full h-auto border border-gray-700 rounded\" id=\"preview-image\"></div><button class=\"bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded mb-4\" id=\"download-btn\">Download PNG</button><div class=\"mt-4 text-gray-500 text-sm\"><p id=\"status\">Last updated: <span id=\"timestamp\"></span></p><p>Press Ctrl+C to stop</p></div></div><script>\n\t\t\tdocument.getElementById('timestamp').textContent = new Date().toLocaleTimeString();\n\t\t\t\n\t\t\tconst downloadBtn = document.getElementById('download-btn');\n\t\t\tdownloadBtn.onclick = function() {\n\t\t\t\tconst link = document.createElement('a');\n\t\t\t\tlink.href = 'data:image/png;base64,' + imageBase64;\n\t\t\t\tlink.download = 'image.png';\n\t\t\t\tlink.click();\n\t\t\t};\n\t\t\t\n\t\t\tconst eventSource = new EventSource('/sse');\n\t\t\t\n\t\t\tconst dot = document.querySelector('#connection-status .rounded-full');\n\t\t\tconst text = document.querySelector('#connection-status span');\n\t\t\t\n\t\t\teventSource.onopen = function() {\n\t\t\t\tdot.classList.remove('bg-red-500');\n\t\t\t\tdot.classList.add('bg-green-500');\n\t\t\t\ttext.textContent = 'Connected';\n\t\t\t};\n\t\t\t\n\t\t\teventSource.onerror = function() {\n\t\t\t\tdot.classList.remove('bg-green-500');\n\t\t\t\tdot.classList.add('bg-red-500');\n\t\t\t\ttext.textContent = 'Disconnected';\n\t\t\t};\n\t\t\t\n\t\t\teventSource.addEventListener('message', function(e) {\n\t\t\t\tconst data = JSON.parse(e.data);\n\t\t\t\tif (data.type === 'image') {\n\t\t\t\t\tdocument.getElementById('preview-image').outerHTML = data.html;\n\t\t\t\t\tdocument.getElementById('timestamp').textContent = new Date().toLocaleTimeString();\n\t\t\t\t} else if (data.type === 'error') {\n\t\t\t\t\talert('Error: ' + data.error);\n\t\t\t\t}\n\t\t\t});\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base("txt2ig - Watch Mode").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
